version: "3.8"

services: 
  mysql:
    image: mysql:8.0 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tareas_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always 
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - mysql
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge