openapi: 3.0.0
info:
  title: API management Tareas
  version: 1.0.0
  description: API to manage tasks with JWT authentication.

servers:
  - url: http://localhost:5000
    description: Local server

paths:
  /api/register:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example2@example.com
                password:
                  type: string
                  example: "example123"
                rol:
                  type: string
                  example: "admin"
      responses:
        '201':
          description: "Successful registration"
        '540':
          description: "Server error"

  /api/login:
    post:
      summary: User login 
      description: Login user with email and password
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - rol
              properties:
                email:
                  type: string
                  format: email
                  description: The email of the user
                  example: example2@example.com
                password:
                  type: string
                  description: The password of the user
                  example: "example123"
      responses:
        '200':
          description: "Successful login"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The message of the login
                    example: "Login successful"
                  token:
                    type: string
                    description: Token JWT
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiZXhhbXBsZUBleGFtcGxlLmNvbSIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzI3Njg4MDAwLCJleHAiOjE3Mjc2OTE2MDB9.b_9sX_Mpr2CkixoOuN6qXxK_Ojgg-uPXlQ6g9xXpTQ8"
        '400':
          description: "Bad request"
        '500':
          description: "Server error"

  /api/logout:
    post:
      summary: User logout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: "Successful logout"
        '500':
          description: "Server error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT     